import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
import {currentUserProfile} from "@/lib/database-helper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BrainDash",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await currentUserProfile();
  console.log(user);

  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
